# Generated by Django 3.1 on 2020-08-23 05:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('test_site', '0003_test_test_result'),
    ]

    operations = [
        migrations.AlterField(
            model_name='test',
            name='test_result',
            field=models.CharField(default='', editable=False, max_length=20, verbose_name='Результат'),
        ),
    ]
