# Generated by Django 3.1 on 2020-08-23 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('test_site', '0004_auto_20200823_1225'),
    ]

    operations = [
        migrations.AddField(
            model_name='test',
            name='url',
            field=models.SlugField(default='', max_length=160, unique=True),
        ),
    ]
