# Generated by Django 3.1 on 2020-11-29 05:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('test_site', '0005_test_url'),
    ]

    operations = [
        migrations.RenameField(
            model_name='question',
            old_name='question_text_1',
            new_name='question_variant_1',
        ),
        migrations.RenameField(
            model_name='question',
            old_name='question_text_2',
            new_name='question_variant_2',
        ),
        migrations.AlterField(
            model_name='question',
            name='answer',
            field=models.CharField(choices=[(1, 'First'), (2, 'Second')], editable=False, max_length=1, verbose_name='Ответ'),
        ),
        migrations.AlterField(
            model_name='test',
            name='title',
            field=models.CharField(max_length=300, verbose_name='Название теста'),
        ),
    ]
